
AWSTemplateFormatVersion: "2010-09-09"
Description:
  Key Management Storage Template
Resources:
  KMSKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: Labs KMS Key
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
        - Sid: AllowIAMPermissions
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: '*'
        - Sid: KeyAdministration
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:user/Nivas.Rajendran.labs'
          Action:
            - 'kms:Create*'
            - 'kms:Describe*'
            - 'kms:Enable*'
            - 'kms:List*'
            - 'kms:Put*'
            - 'kms:Update*'
            - 'kms:Revoke*'
            - 'kms:Disable*'
            - 'kms:Get*'
            - 'kms:Delete*'
            - 'kms:ScheduleKeyDeletion'
            - 'kms:CancelKeyDeletion'
          Resource: '*'
        - Sid: KeyUsage
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:user/Nivas.Rajendran.labs'
          Action:
            - 'kms:DescribeKey'
            - 'kms:Encrypt'
            - 'kms:Decrypt'
            - 'kms:ReEncrypt*'
            - 'kms:GenerateDataKey'
            - 'kms:GenerateDataKeyWithoutPlaintext'
          Resource: '*'
  KeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: alias/Labs10Key
      TargetKeyId: !Ref KMSKey

Outputs:
  MyAccountId:
    Value: !Ref 'AWS::AccountId'
    Export:
      Name: NivasAccountId
